import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-900 text-white">
        <header className="w-full bg-neutral-800/60 backdrop-blur-sm border-b border-neutral-700">
          <div className="max-w-7xl mx-auto px-4 py-3 flex items-center gap-4">
            <Link href="/" className="flex items-center gap-3 hover:opacity-90">
              <span className="sr-only">Home</span>
              <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7 text-red-500" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 3l9 8h-3v7a2 2 0 0 1-2 2h-4v-6H10v6H6a2 2 0 0 1-2-2v-7H1l11-8z" />
              </svg>
              <span className="font-semibold text-lg">Galería</span>
            </Link>
          </div>
        </header>

        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
